# SPDX-License-Identifier: GPL-3.0-or-later
file(REMOVE_RECURSE "${ROOT}")
file(MAKE_DIRECTORY "${ROOT}")
set(ENV{XDG_CONFIG_HOME} "${ROOT}")
set(ENV{GSETTINGS_BACKEND} "memory")
execute_process(COMMAND "${CLI}" --clock standard-24 RESULT_VARIABLE status OUTPUT_QUIET)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Initial CLI write failed")
endif()
file(READ "${ROOT}/infiltrator/presentation.conf" before)
execute_process(COMMAND "${CLI}" --clock decimal --calendar invalid RESULT_VARIABLE status OUTPUT_QUIET ERROR_QUIET)
if(status EQUAL 0)
    message(FATAL_ERROR "Malformed command succeeded")
endif()
file(READ "${ROOT}/infiltrator/presentation.conf" after)
if(NOT before STREQUAL after)
    message(FATAL_ERROR "Failed command partially persisted earlier options")
endif()
execute_process(COMMAND "${CLI}" --clock decimal --seconds on RESULT_VARIABLE status OUTPUT_QUIET)
if(NOT status EQUAL 0)
    message(FATAL_ERROR "Valid multi-option command failed")
endif()
file(READ "${ROOT}/infiltrator/presentation.conf" after)
if(NOT after MATCHES "clock-mode=decimal" OR NOT after MATCHES "show-seconds=true")
    message(FATAL_ERROR "Multi-option transaction lost a setting")
endif()
file(REMOVE_RECURSE "${ROOT}")
